name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests and generate coverage report
      run: |
        pytest --cov=backend --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  
        file: ./coverage.xml  
        flags: unittests
        name: codecov-umbrella
    - name: Deploy to Heroku
      if: github.ref == 'refs/heads/main' && job.status == 'success'
      run: |
        wget -qO- https://cli-assets.heroku.com/install.sh | sh
        heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}
        git push heroku HEAD:main
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
